### ISSUE TITLE
بعدما vs بعد ما and لوما vs لو ما and Word Count

### ISSUE THREAD

**Issue by bytefect** [heliwave/QuranCode#2]
مرحباً دكتور علي، شكراً على كل الأبحاث والمجهودات التي تقوم بها، الله يحفظك ويزيدك نور في نور. هناك مشكل في العد، في الإصدار الأخير، البرنامج لا يظهر مجموع عدد الكلمات 77432 يظهر فقط 77430 كلمة، بنظام 29 بدون البسملة الغير المرقمة، في سورة البقرة يظهر فقط 6116 كلمة وفي سورة الأنفال يظهر فقط 1233 كلمة، بينما في اصدار 6.19.719.2 يظهر في سورة البقرة 6117 كلمة وفي سورة الأنفال 1234 كلمة، وكون مجموع الكلمات في ذلك الاصدار 77432 كلمة، تحياتي العطرة

**Comment by heliwave** [comment]
Three بعد ما changed to بعدما
One لوما changed to لو ما

٢_١٨١	فمن بدله بعدما سمعه فانما اثمه علي الذين يبدلونه ان الله سميع عليم
٨_٦	يجدلونك في الحق بعدما تبين كانما يساقون الي الموت وهم ينظرون
١٣_٣٧	وكذلك انزلنه حكما عربيا ولين اتبعت اهواءهم بعدما جاءك من العلم ما لك من الله من ولي ولا واق
١٥_٧	لو ما تاتينا بالمليكه ان كنت من الصدقين

**Comment by bytefect** [comment]
Anytime brother,
Thank you brother,

Here's why I think it's 77432 words, and why the release 6.19.719.2 has it right, and what proves the authenticity of the given word count and of the entire Quran in terms of its Quranic spelling. A recent discovery while I was attempting to find a way to prove its authenticity. ليطمئن قلبي

يقول سبحانه وتعالى: ( انا نحن نزلنا الذكر وانا له لحفظون ) 15:9
وتتكون هذه الآية من 7 كلمات مما يعني أن القرءان حفظ بنظام 7
وفي نفس السورة آية أخرى ( ولقد ءاتينك سبعا من المثاني والقرءان العظيم ) 15:87
وتدل أيضاً على نظام 7
74:30 (عليها تسعه عشر) والآية التالية
والتي تدل على نظام 19
والآن العمليات

صف عدد آيات كل سورة بدءاً بسورة الفاتحة 7 آيات وانتهاءً بسورة الناس 6 آيات
7286...............6  / 7 = 0 يعطي عدد يتكون من 227 رقم يقبل القسمة على 7 بدون باقي
Simplified29 نظام
Abjad_Gematria مع إعطاء الهمزة قيمة 1
صف قيمة كل كلمة من بسم إلى الناس يعطي عدد طويل يتكون من 205981 رقم يقبل القسمة على 7 بدون باقي
وعكس عملية تسلسل هذا الصف، صف قيمة كل كلمة من الناس إلى بسم يعطي عدد طويل يتكون من 205981 رقم يقبل القسمة على 19 بدون باقي
هناك 6236 آية مرقمة و112 آية غير مرقمة
عدد السور + عدد الآيات المرقمة + عدد الكلمات + عدد الحروف بدون احتساب الهمزة الأصلية
114 6236 77432 322604
محمد صلى الله عليه وسلم
عملية الجمع الرقمية
114 6236 = 1+1+4+6+2+3+6 = 23 = عدد سنوات الوحي القرءاني 13 سنة في مكة و 10 سنوات في المدينة
77432 322604 = 7+7+4+3+2+3+2+2+6+0+4 = 40 = عمر النبي محمد عندما نزل عليه الوحي
114 6236 77432 322604 = 1+1+4+6+2+3+6+7+7+4+3+2+3+2+2+6+0+4 = 63 عمر النبي عند وفاته
114623677432322604 هذا العدد يتكون من 18 رقماً يقبل القسمة على 7 وعلى 63 بدون باقي
إضافة عدد سنوات الوحي القرءاني على هذا الصف
114 6236 77432 322604 23
11462367743232260423
هذا العدد يتكون من 20 رقم يقبل القسمة على 19 بدون باقي
114 6236 77432 322604
وعكس تسلسل هذا الصف + عدد سنوات الوحي القرءاني
322604 77432 6236 114 23
32260477432623611423 هذا العدد يتكون من 20 رقم يقبل القسمة على 7 و 19 بدون باقي

عدد حروف القرءان بدون احتساب الهمزة الأصلية 322604 حرف، عدد الكلمات 77432، عدد الآيات 6236
عدد السور 114
114 6236 77432 322604 صفها مع بعضها
114623677432322604
بالإضافة إلى أن هذا العدد يقبل القسمة على 7 و63 بدون باقي و 63 هو عمر النبي عند وفاته 
فإن عكس تسلسل هذا الصف مع إضافة الهمزة الأصلية إلى مجموع الحروف يصبح (3060+322604) 325664
325664 77432 6236 114
325664774326236114
يقبل القسمة على 7 و 63 بدون باقي
Simplified29 نظام
Frequency_Linear  عوض القيمة 20، هنا يكمن المفتاح بحيث نعطي الهمزة قيمة 1
وصف قيمة كل كلمة من كلمات القرءان من بسم إلى الناس بنظام التكرار الخطي مع احتساب الهمزة 1 يعطي عدد طويل يتكون من 144427 رقم يقبل القسمة على 7 وعلى 63 بدون باقي
 وصف قيمة مجموع الكلمات في كل آية من آخر آية إلى أول آية بحيث قيمة آخر آية 67 وأول آية 114
يعطي عدد طويل يتكون من 18386 رقم يقبل القسمة على 7 وعلى 63 بدون باقي
وأفكر على أن هذا دليل يثبت صحة وسلامة مصحف المدينة النبوية (حفص) من التحريف من ناحية الإملاء القرءاني
وعدم تطابق الإملاء والحروف المستبدلة وترتيب عد الآيات المتبع في رواية ورش مع هذا النظام العظيم والعجيب
بحيث بمجرد تغيير حرف واحد أو كلمة واحدة ينهار هذا النظام المتكامل
وبه صدق الله العظيم، قوله تعالى، (انا نحن نزلنا الذكر وانا له لحفظون) 15:9
75:17 (ان علينا جمعه وقرءانه)

سلامي، تحياتي ومودتي

**Comment by heliwave** [comment]
Salam dear brother and thank you for all the above patterns.
I have an even more convincing pattern that the new word count is the correct one but first a question :)

How many 4-chapter groups do you think there are where each 4-chapter group has the sum of its 4 chapters = 229 and sum of its 4 chapter verses = 229? Answer is 229 !!!

Out of these 229 4-chapter groups there are 16 with sum of 4 chapter words = prime number with prime digit sum (i.e. additive prime) and 53 with sum of 4 chapter words = composite number with non-composite digit sum (i.e. non-additive composite) where:

114 / 2 = 57
Median(1..57) = 29
57*29 = 1653
the 16th prime number = 53
AND
there are 16 additive prime number up to 114
there are 53 additive composite number up to 114

See
http://heliwave.com/506.txt
http://heliwave.com/561.txt
http://heliwave.com/263.txt
http://heliwave.com/114.txt

**Comment by heliwave** [comment]
I have changed the title so future readers know exactly what is being discussed.
Thank you for understanding ...

**Comment by bytefect** [comment]
You are welcome dear brother,
Thank you doctor Ali for all the links,

I understand, I'm sorry about the previous title, it was a mistake, I realize that it was misleading, and thank you so much for changing it to an appropriate title.

Happy Ramadan with all the wishes.

I think I need time to answer that question, and I came to an insight which is: What if the issue here
is not an issue of whether there is 77432 or 77430 words, and is an issue of misidentifying names, that 77432 is something else, 77432 something, like 77432 units, and 77430 words. The more I delve into this, the more I realize that the Quran is a flexible entity, it adapts to different systems, depending on the system projected on it.

Thank you,

سلامي، تحياتي ومودتي

**Comment by heliwave** [comment]
You are most welcome dear brother and I STRONGLY believe that the Quran Text is in fact SEVEN Texts overlapping each other and hence multiple patterns from different domains (قراءات) intermixed with each other to make it impossible to decrypt/unlock.

The outer Quran (القرءان العظيم) is truly an encrypted document that stays READABLE despite encryption.
Decrypting It (by Al-Mutaharoon only) will unveil (in sha Allah) the Hidden Quran (القرءان الكريم).

Just two weeks ago someone sent me something really amazing where he found out the exact number of letters of the Quran including ALL hamzas from surat Al-Fatiha only and a very simple way:
Sum = 0
For each verse V with W words and L letters
Sum += 2(W^2) + 2(L^2) + 3(L^3)
where the final Sum = 328287 = Quran's letters including 495 hamza above horizontal line (which researchers argue if they should be real Hamza and thus countable or superscript hamza and thus non-countable).

However, without these 495 hamzas above horizontal lines, the number of letters in all repeated verses in the Quran = 6555 = Sum of all chapter numbers from 1 to 114.

All I can do is add options in QuranCode software to cater for all researchers.
See the latest version (6.19.1039) with seven options for Bism, Waw, Shadda, Hamza, Elf, Yaa, Noon variables.

In your case, if you still want to change these four words from (3 بعدما and 1 لو ما) to (3 بعد ما and 1 لوما) you can edit the Rules *.txt files to suit your need. Notice that currently "Min Ba3di Ma" is three words whereas "Ba3dama" (with fat'ha) is one word.

Another big issue Malekum vs Ma Lekum, but that is for another post :)

Al-hamdu liAllah and Ramadhaan kareem to you and yours,

Allah knows all.

**Comment by bytefect** [comment]
Salam dear brother and master, sorry for taking a long time to answer back, but maybe the reply was meant to be at this time. Thank you very much for the data, and the miraculous equation, it explains a lot. I don't know the number and how to get to the number of those 4-chapter groups, but until then, I'll just take your word for it.

The number of letters I gave at that time was limited by the context, and thanks to your data, it is indeed incomplete in relation to the total number of letters.

From the previous system of 77432 units, the patterns, and the equation. I think they were there so that we can understand the numbered unit versus the unnumbered unit.
I understand that just as there are unnumbered verses, there are also unnumbered words, and unnumbered letters.
So there are 6236 numbered verses, and 112 unnumbered verses.
448 unnumbered words pertain to the unnumbered verses.
2128 unnumbered letters pertain to the unnumbered verses.
325664 numbered letters pertain to the numbered verses.
495 unnumbered letters pertain to the numbered verses.
326159 letters pertain to the numbered verses, and 2128 letters pertain to the unnumbered verses.
328287 letters pertain to all the 6348 verses. (6236+112)

I presented the theory for the total of numbered words to be equal to 77432 numbered words,
(Notice 7+7 = 14 = 5, 5432, it's like a series) however it turns out that it is false, because those weren't the total of numbered words but units of encryption pertaining to another system, and because of another data that became available to me, that proves that the total of numbered words is 77407 numbered words.

Master Ameer proved it using much data,
like, 6:115 { وَتَمَّتْ كَلِمَتُ رَبِّكَ صِدْقًۭا وَعَدْلًۭا ۚ لَّا مُبَدِّلَ لِكَلِمَٰتِهِۦ ۚ وَهُوَ ٱلسَّمِيعُ ٱلْعَلِيمُ }
but his page was taken down. You can contact him from here to send you the proofs.
https://www.facebook.com/ameer.alborihi
This is one of his cached posts:
https://webcache.googleusercontent.com/search?q=cache:kfxBUoe8_ncJ:https://apps.z.facebook.com/menasraralquran/photos/a.390168651833551/511757009674714

https://www.facebook.com/groups/AlRaqeemQuranMiracles/permalink/2116741105110462/

And as it is used here by master Abd Alkhaliq:
https://www.facebook.com/notes/2345294869038738

(I think that 77407 is also used as a constant.)

And as it is used here, for the 58631th word, which won't be the same word in other systems:
https://www.facebook.com/Behind.Numbersss/posts/1769203256557111

The Noon Center For Quran Researches and Studies:
http://www.islamnoon.com/Nashrat/kawaed.htm

And these are the changes to be made in order to convert to 77407 numbered words:
2:181:3	بَعْدَمَا	to	بَعْدَ مَا
8:6:4	بَعْدَمَا	to	بَعْدَ مَا
13:37:8	بَعْدَمَا	to	بَعْدَ مَا

15:7:1	لَّوْ	15:7:2	مَا	to	لَّوْمَا

ما in the context of negation stays separated,
however, it is joined in the interrogative context, such as:
{ مَالِ هَٰذَا ٱلرَّسُولِ } part of 25:7 - (مَالِ) is already one word.
{ مَالِ هَٰذَا ٱلْكِتَٰبِ } part of 18:49 - (مَالِ) is already one word.
{ فَمَالِ ٱلَّذِينَ كَفَرُوا۟ } part of 70:36 - (فَمَالِ) is already one word.
which applies to the interrogative ما + ل
Or Yما + لX

12:11:3	مَا	12:11:4	لَكَ	to	مَالَكَ
15:32:3	مَا	15:32:4	لَكَ	to	مَالَكَ
4:75:1	وَمَا	4:75:2	لَكُمْ	to	وَمَالَكُمْ
6:119:1	وَمَا	6:119:2	لَكُمْ	to	وَمَالَكُمْ
9:38:4	مَا	9:38:5	لَكُمْ	to	مَالَكُمْ
37:25:1	مَا	37:25:2	لَكُمْ	to	مَالَكُمْ
37:92:1	مَا	37:92:2	لَكُمْ	to	مَالَكُمْ
37:154:1	مَا	37:154:2	لَكُمْ	to	مَالَكُمْ
57:8:1	وَمَا	57:8:2	لَكُمْ	to	وَمَالَكُمْ
57:10:1	وَمَا	57:10:2	لَكُمْ	to	وَمَالَكُمْ
68:36:1	مَا	68:36:2	لَكُمْ	to	مَالَكُمْ
71:13:1	مَّا	71:13:2	لَكُمْ	to	مَّالَكُمْ
10:35:26	فَمَا	10:35:27	لَكُمْ	to	فَمَالَكُمْ
4:88:1	فَمَا	4:88:2	لَكُمْ	to	فَمَالَكُمْ
99:3:3	مَا	99:3:4	لَهَا	to	مَالَهَا
2:246:32	وَمَا	2:246:33	لَنَآ	to	وَمَالَنَآ
5:84:1	وَمَا	5:84:2	لَنَا	to	وَمَالَنَا
14:12:1	وَمَا	14:12:2	لَنَآ	to	وَمَالَنَآ
27:20:4	مَا	27:20:5	لِىَ	to	مَالِىَ
36:22:1	وَمَا	36:22:2	لِىَ	to	وَمَالِىَ
38:62:2	مَا	38:62:3	لَنَا	to	مَالَنَا
40:41:2	مَا	40:41:3	لِىٓ	to	مَالِىٓ
74:49:1	فَمَا	74:49:2	لَهُمْ	to	فَمَالَهُمْ
84:20:1	فَمَا	84:20:2	لَهُمْ	to	فَمَالَهُمْ
8:34:1	وَمَا	8:34:2	لَهُمْ	to	وَمَالَهُمْ

**Comment by bytefect** [comment]
(reminder)

**Comment by heliwave** [comment]
Dear brother,

Summary:
God glory to Him, uses a non-Arabic "writing" but keeps it perfectly Arabic-sounding". So don;t dream of changing the Quran Text for the sake of any external rule.

Details:
The Quran's Text is produced mathematically from the inner Quran Kareem. It is not meant to be Arabic writing but Arabic sounding only.

What Noon Center are doing is corrupting the Text to make it follow the Arabic language but God never said "Arabic Book", only "Arabic Quran == Arabic Sound == Arabic Recitation".

It is easy to "correct" the existence of the space between ما and لكم based on Arabic rules of writing:
ما لكم Ma Lekum (What is the matter with you ..?) for questions.
مالكم Malekum (You don't have ...) for statements.
thinking it was an error by the writers of the Quran.

However, it is impossible to "correct" the existence of the space between ما and أين based on Arabic rules of writing because the shape of letter ن changes and the writers of the Quran and all people revising it would see the "error" immediately.
أين ما Ayna Ma (Where is that thing ...?)
أينما Aynama (Wherever ....)
See the Appendixes at the end of http://heliwave.com/EncryptedQuran.pdf
 
Dear brother, **STICK TO THE TEXT AS IS** if you want guidance from the One Who knows all and please always believe in the Quran as it is and always say:
**"We believe in it all. All is from God"** be of the "firmly grounded in knowledge" or **ٱلرَّٰسِخُونَ فِى ٱلْعِلْمِ**, not like the misguided people at Noon Center.

_٣_٧	هُوَ ٱلَّذِىٓ أَنزَلَ عَلَيْكَ ٱلْكِتَٰبَ مِنْهُ ءَايَٰتٌۭ مُّحْكَمَٰتٌ هُنَّ أُمُّ ٱلْكِتَٰبِ وَأُخَرُ مُتَشَٰبِهَٰتٌۭ ۖ فَأَمَّا ٱلَّذِينَ فِى قُلُوبِهِمْ زَيْغٌۭ فَيَتَّبِعُونَ مَا تَشَٰبَهَ مِنْهُ ٱبْتِغَآءَ ٱلْفِتْنَةِ وَٱبْتِغَآءَ تَأْوِيلِهِۦ ۗ وَمَا يَعْلَمُ تَأْوِيلَهُۥٓ إِلَّا ٱللَّهُ ۗ وَٱلرَّٰسِخُونَ فِى ٱلْعِلْمِ يَقُولُونَ ءَامَنَّا بِهِۦ كُلٌّۭ مِّنْ عِندِ رَبِّنَا ۗ وَمَا يَذَّكَّرُ إِلَّآ أُو۟لُوا۟ ٱلْأَلْبَٰبِ
003:007 It is He who has sent down to you the Book. Parts of it are definitive verses, which are the mother of the Book, while others are metaphorical. As for those in whose hearts is deviance, they pursue what is metaphorical in it, courting temptation, and seeking its interpretation. But no one knows its interpretation except Allah and those firmly grounded in knowledge; they say, ‘We believe in it; all of it is from our Lord.’ And none takes admonition except those who possess intellect.

٤_١٦٢	لَّٰكِنِ ٱلرَّٰسِخُونَ فِى ٱلْعِلْمِ مِنْهُمْ وَٱلْمُؤْمِنُونَ يُؤْمِنُونَ بِمَآ أُنزِلَ إِلَيْكَ وَمَآ أُنزِلَ مِن قَبْلِكَ ۚ وَٱلْمُقِيمِينَ ٱلصَّلَوٰةَ ۚ وَٱلْمُؤْتُونَ ٱلزَّكَوٰةَ وَٱلْمُؤْمِنُونَ بِٱللَّهِ وَٱلْيَوْمِ ٱلْءَاخِرِ أُو۟لَٰٓئِكَ سَنُؤْتِيهِمْ أَجْرًا عَظِيمًا
004:162 But as for those who are firmly grounded in knowledge from among them, and the faithful, they believe in what has been sent down to you, and what was sent down before you—those who maintain the prayer, give the zakat, and believe in Allah and the Last Day—them We shall give a great reward."_

THESE ARE NOT ERRORS. THEY ARE ALL PART OF THE CODE.
Please see how sensitive the code to the locations of letters/words/verses/chapters and distances-between-same letters/words/verses:

لكل حرف وكلمة وءاية وسورة مواقع ومسافات عن مثيلاتها تشكل نظاماً مُحكماً وكما يلي:
لكل حرف أربع مواقع (في كلمته، في ءايته، في سورته، وفي الكتاب) وأربع مسافات عن مثيله السابق (حروف ، كلمات ، ءايات ، وسُوَر).
لكل كلمة ثلاث مواقع (في ءايتها، في سورتها، وفي الكتاب) وثلاث مسافات عن مثيلتها السابقة (كلمات، ءايات ، وسُوَر).
لكل ءاية موقعين (في سورتها، وفي الكتاب) ومسافتين عن مثيلتها السابقة (ءايات، وسُوَر).
لكل سورة موقع (في الكتاب) ولا مثيل لها فلا مسافة.

01. letter position in its word.
02. letter position in its verse.
03. letter position in its chapter.
04. letter position in the Quran.
05. letter distance to previous/next exact letter in letters.
06. letter distance to previous/next exact letter in words.
07. letter distance to previous/next exact letter in verses.
08. letter distance to previous/next exact letter in chapters.
09. word position in its verse.
10. word position in its chapter.
11. word position in the Quran.
12. word distance to previous/next exact word in words.
13. word distance to previous/next exact word in verses.
14. word distance to previous/next exact word in chapters.
15. verse position in its chapter.
16. verse position in the Quran.
17. verse distance to previous/next exact verse in verses.
18. verse distance to previous/next exact verse in chapters.
19. chapter position in the Quran.

---------------------
رجاء إقرأ لتعلم سر الكتابة الرحمانية حيث هنالك 19 متغير يحمي النص
http://heliwave.com/114_AR.pdf

Ali

**Comment by bytefect** [comment]
Thank you very much for the links and everything, dear brother and master Ali.
